# General
nqubits: 700000000000
state: "DMatrix"
etime: True
# Target Hamiltonian
observable:
  def: "ising"
  coefficients:
    cn: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    bn: [0, 0, 0, 0, 0, 0, 0]
    r: 0
# Optimization
optimization:
  status: False
  algorithm: "SLSQP"
  iteration: 4
  constraint: False
# Circuit config
ansatz:
  draw: False # Draw the circuit
  layer: 30
  gateset: 1
  unitary: 
    def: "xy"
    coefficients:
      cn: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      bn: [0, 0, 0, 0, 0, 0, 0]
      r: 0
    time:
      min: 0.0
      max: 10.0
  noise:
    status: True
    value: [0.001, 0.001, 0.001, 0.001] # Noise probabilities for [r, cz, u, y] gates.
    factor: [3, 3, 3, 0] # Noise identity factors for [r, u, y, cz] gates
param: "random"