run: "vqe"
fprefix: "test"
# Variational quantum eigensolver config
vqe:
  # System
  nqubits: 4
  state: "statevector"
  # Target Hamiltonian
  observable:
    def: "ising"
    coefficients:
      cn: [1.0, 1.0, 1.0]
      bn: [0, 0, 0, 0]
      r: 0
  # Optimization
  optimization:
    status: True
    algorithm: "SLSQP"
    iteration: 2
    constraint: False
  # Circuit config
  ansatz:
    draw: True # Draw the circuit
    type: "xy"
    layer: 10
    gateset: 1
    ugate: 
      coefficients:
        cn: [1.0, 1.0, 1.0]
        bn: [0, 0, 0, 0]
        r: 0
      time:
        min: 0.0
        max: 10.0
    noise:
      status: True
      value: [0.01, 0.01, 0.01, 0.01] # Noise probabilities for [r, cz, u, y] gates.
  param: "random"
# Zero noise extrapolation config
zne:
  extrapolation:
    method: "Richardson"
    degrees: [1, 2, 3, 4, 5]
  redundant_ansatz:
    # Identity factors for the redundant ansatz
    identity_factors: [
      [0, 0, 0, 0], [1, 0, 0, 0]
    ]
