run: "vqe"
# System
nqubits: 7
state: "dmatrix"
# Target Hamiltonian
observable:
  def: "ising"
  coefficients:
    cn: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    bn: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    r: 0
# Output
output:
  file_name_prefix: "vqe_vals_q7_l30_n1"
  fig_dpi: 100
# Variational quantum eigensolver config
vqe:
  # Optimization
  optimization:
    status: True
    algorithm: "SLSQP"
    iteration: 9
    constraint: False
  # Circuit config
  ansatz:
    draw: True # Draw the circuit
    type: "xy"
    layer: 30
    gateset: 1
    ugate: 
      coefficients:
        cn: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        bn: [0, 0, 0, 0, 0, 0, 0]
        r: 0
      time:
        min: 0.0
        max: 10.0
    noise:
      status: False
      value: [0, 0, 0, 0] # Noise probabilities for [r, cz, u, y] gates.
# Zero noise extrapolation config
zne:
  extrapolation:
    method: "Richardson"
    degrees: [1, 2, 3, 4, 5]
    sampling: "default"
  redundant_ansatz:
    # Identity factors for the redundant ansatz
    identity_factors: [
    [0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 1, 1], [2, 0, 0], [2, 1, 0], [2, 1, 1], [2, 2, 0], [2, 2, 1], [2, 2, 2], 
    [3, 0, 0], [3, 1, 0], [3, 1, 1], [3, 2, 0], [3, 2, 1], [3, 2, 2], [3, 3, 0], [3, 3, 1], [3, 3, 2], 
    [3, 3, 3], [4, 0, 0], [4, 1, 0], [4, 1, 1], [4, 2, 0], [4, 2, 1], [4, 2, 2], [4, 3, 0], [4, 3, 1], 
    [4, 3, 2], [4, 3, 3], [4, 4, 0], [4, 4, 1], [4, 4, 2], [4, 4, 3], [4, 4, 4], [5, 0, 0], [5, 1, 0], 
    [5, 1, 1], [5, 2, 0], [5, 2, 1], [5, 2, 2], [5, 3, 0], [5, 3, 1], [5, 3, 2], [5, 3, 3], [5, 4, 0], 
    [5, 4, 1], [5, 4, 2], [5, 4, 3], [5, 4, 4], [5, 5, 0], [5, 5, 1], [5, 5, 2], [5, 5, 3], [5, 5, 4], 
    [5, 5, 5]
]
 # Identity factor for rotation gate, unitary gate and Y gate

# Initial parameters for the ansatz
param: "random"