# Run configurations: Choose from 'vqe', 'redundant', and 'zne'
run: "redundant"

# System configuration
nqubits: 4
state: "dmatrix"

# Target Hamiltonian configuration
observable:
  # Def: 'custom', 'ising', 'xy_model-xz-y', or 'heisenberg'.
  # 'custom' is created using the definition of 'xy_model-xz-y', which is an XY-model Hamiltonian.
  def: "ising"
  # WARNING: Coefficients are only applicable for 'def: custom', and will be overwritten if 'def' is specified as an in-built: 'ising', 'xy_model-xz-y', or 'heisenberg'.
  coefficients:
    cn: [0.5, 0.5, 0.5]
    bn: [1.0, 1.0, 1.0, 1.0]
    r: 1

# Output configuration
output:
  file_name_prefix: "Ztest"
  draw:
    status: True
    fig_dpi: 100
    type: "png"

# (1) Variational Quantum Eigensolver (VQE) configuration
vqe:
  iteration: 3

  # Optimization configuration
  optimization:
    status: True
    algorithm: "SLSQP"
    constraint: False

  # Circuit configuration
  ansatz:
    type: "xy_model-xz-y"
    layer: 1
    gateset: 1
    ugate: 
      coefficients:
        cn: [0.5, 0.5, 0.5]
        bn: [0, 0, 0, 0]
        r: 0
      time:
        min: 0.0
        max: 10.0
    noise:
      status: True
      value: [0, 0, 0, 0] # Noise probabilities for [r, cz, u, y] gates.

    # Initial parameters for the ansatz
    init_param: "random"
# (2) Redundant circuit configuration

  # Identity factors for r, U, Y, and CZ gates
  # WARNING: Identity scaling for the U gate is only possible if vqe.ansatz.type: 'xy_model-xz-y'. For other types, the identity factor for the U gate must be set to 0.
identity_factors: [
    [1, 0, 0, 1], [0, 1, 2, 1]
]

# (3) Zero noise extrapolation (ZNE) configuration
zne:
  # Choose method: 'linear', 'polynomial', 'richardson', or 'richardson-mul'
  # 'linear' and 'polynomial' use scikit-learn for regression. 
  method: "linear"

  # Degree is only applicable for 'polynomial' and 'richardson-mul'. For 'richardson', degree is computed based on the number of data points.
  degree: 1

  # Sampling method: 'default', 'default-N', or 'random-N', where N is an integer.
  # 'default' - samples all points.
  # 'default-N' - samples first N points.
  # 'random-N' - samples N points randomly.
  sampling: "default-5"
  
  # Data points for extrapolation
  data_points: 